[
   SortVar                  -- _1,
   SortNoArgs               -- _1,
   Sort                     -- _1 KW["("] _2 KW[")"],
   Sort.2:iter-star-sep     -- _1 KW[","],
   TypeDecl                 -- _1 _2 _3,
   TypeDeclQ                -- _1 _2 _3,
   Str                      -- _1,
   NoTypeParams             -- ,
   TypeParams               -- KW["("] _1 KW[")"],
   TypeParams.1:iter-sep    -- _1 KW[","],
   TypeParam                -- _1 KW[":"] _2,
   Var                      -- _1,
   Self                     -- KW["self"],
   Self                     -- KW["self"],
   Wld                      -- KW["_"],
   Int                      -- _1,
   Real                     -- _1,
   Str                      -- _1,
   Op                       -- _1 KW["("] _2 KW[")"],
   Op.2:iter-star-sep       -- _1 KW[","],
   OpQ                      -- _1 KW["("] _2 KW[")"],
   OpQ.2:iter-star-sep      -- _1 KW[","],
   NoAnnoList               -- _1,
   ListVar                  -- _1,
   Var                      -- _1,
   Char                     -- _1,
   List                     -- KW["["] _1 KW["]"],
   List.1:iter-star-sep     -- _1 KW[","],
   ListTail                 -- KW["["] _1 KW["|"] _2 KW["]"],
   ListTail.1:iter-star-sep -- _1 KW[","],
   TypeDef                  -- KW["module"] _1 _2,
   TypeDef.2:iter-star      -- _1,
   SigPart                  -- V  [H  [KW["signatures"]] _1],
   SigPart.1:iter-star      -- _1,
   TypePart                 -- V  [H  [KW["types"]] _1],
   TypePart.1:iter-star     -- _1,
   RulePart                 -- V  [H  [KW["rules"]] _1],
   RulePart.1:iter-star     -- _1,
   Import                   -- _1,
   DefaultRelation          -- KW["<:"],
   TypeRule                 -- _1 _2 _3 KW[":"] _4,
   TypeRule.1:iter-sep      -- _1 KW["&"],
   RelationRule             -- _1 _2 _3 _4 _5,
   RelationRule.1:iter-sep  -- _1 KW["&"],
   CheckRule                -- _1 _2 _3,
   CheckRule.1:iter-sep     -- _1 KW["&"],
   TypeCheck                -- _1 KW[":"] _2,
   Resolve                  -- KW["@"] _1 KW["="] _2,
   ResolveCheck             -- KW["@"] _1 KW[":"] _2,
   Relation                 -- _1 _2 _3,
   Map                      -- KW["map"] _1,
   Strategy                 -- _1,
   SVar                     -- _1,
   Appl                     -- KW["<"] _1 KW[">"] _2,
   AM                       -- _1 KW["=>"] _2,
   Error                    -- _1 _2,
   Type                     -- _1 KW["->"] _2,
   Type.1:iter-sep          -- _1 KW["*"]
]